### PR TITLE
Paper37

### PR DESCRIPTION
**Pull request by jacobkrueger**
We would like to apply for the reusable and available badges for Paper 37. I added the submission folder etc. manually, as they have been missing. We registered a DOI for a Zenodo repository for the paper, which we did not publish yet to be able to adapt the files if requested by the reviewers.

### CODE REVIEW

**Comment by JonDoe-ArtifactsTrack** [comment]
Dear Authors,
i have checked your files and they are surely available. I have has some problems with your  R script.
As you can see in the file attached below, running the script I got different kinds of errors and exceptions. 
Please add the necessary information to use and run your R script (version of R needed, in which directory the R script must be run, if it is necessary to pass some arguments to the Script etc. ).

Thanks.
[outputRScript.txt](https://github.com/se-conf/icsme20-artifacts-and-rose/files/5080156/outputRScript.txt)

**Comment by jacobkrueger** [comment]
Dear Reviewer,
I am sorry, but I cannot fully tell what the problem is, since some error messages are not in English (Spanish or Portuguese, maybe?).

However, it seems that you do not have the loaded packages installed in your R environment (the most recent, but also older ones, should all work fine). If you are using RStudio, you can use the Tools -> Install Packages tab to search for the packages in the library(<>) commands and let R install them and all their dependencies. You can also add such commands, like install.packages("ggplot2") to install packages (here, ggplot2). This should also work.

One more remark, the loadfonts package may require that the commented line font_import() is run once (afterwards, it can again be commented out) to load other font types (we are using computer modern).

I hope this helps solve the problem!

Kind regards

**Comment by JonDoe-ArtifactsTrack** [comment]
Dear authors,
i have checked the updated files, it is all ok now. However i suggest you improve the explanation for installing the files a bit. Moreover I suggest you add some information in the documentation to ease the installation of the packages which are done manually. (eg. read the script, identify the libraries, install them manually, remember to change the work folder, etc. leads you to execute the file. 

the artifacts are surely available and they are reusable so i would champion the badge requested for this artifact. 

kind regards.

**Comment by klainfo** [comment]
Thank you for submitting the artefact to the ICSME'20 Artifact/Rose Track. Congratulations! Two reviewers agreed that the artefact is reusable and available.

-----------------------------

Submission ID: # 37
Decision: [Accept, Reject]: ACCEPT
Recommended for Best Artifact Awards: No
Score (out of 10): 8
Comments: w.r.t. Badge Rubrics: the package is surely available with all the artifacts necessary to install. The description and instructions provided for the installation can be improved and provide more details for manual installation of the files (in the end a researcher manages to install everything but a more straightforward description would be helpful). However I feel that both badges can be assigned: AVAILABLE and REUSABLE.

-----------------------------

Submission ID: #37 
Decision: [Accept] 
Recommended for Best Artifact Awards: No 
Score (out of 10): 7

Reviewer's comments
The authors have submitted the following artifacts contained in 3 folders for their ICSME2020 paper titled: "What Developers (Care to) Know About Their System".:

1. InterviewData
- Correctness_Code.csv
- Correctness_Model.csv
- Correctness.csv
- IK1.csv
- IK2.csv
- IK3.csv
- IK4_5.csv
- IntervieweesMeta.csv
- OS1-4.csv
- SurveyTemplate.pdf
- TimesScinceFileEdit.csv

2. LiteratureData
- Collection_raw.csv
- Ratings.csv
- Reclassification.csv
- ThemesFromClassifications.csv

3. R
- assVsCorr_new.csv
- ClustersFromPapers.csv
- ClustersFromQuestions.csv
- fileTimes_PairedForTest.csv
- importanceVScorrectnessTESTdata_new.csv
- NormalizedRatings.csv
- overallImportance.csv
- questionsRatings_new.csv
- script.R

The files and scripts submitted by the authors are available. The graphs including statistical results generated from the script conform to the results published in the original paper. It is also possible to reuse the artifacts to reproduce the results contained in the paper.

Some bugs do exist in the R script, however it takes a minimal effort of approximately 10-20mins to find the bugs and fix them in the submitted R script. 

Some errors in the R script:
Error in cor.test(test_framex, test_framey, method = "kendall", exact = TRUE,  : 
  object 'test_framex' not found

The function cor.test(test_framex,test_framey,method = "kendall",exact=TRUE,continuity = FALSE,conf.level = 0.95).

Apparently there was no object test_framex or test_framey created before calling this function.
I had to create these two objects below to get it working:
test_framex <- test_frame$Importance
test_framey <- test_frame$Correctness
It is my assumption that test_framex and test_framey correspond to those two classes.

Authors should be aware that the scripts ggplot library may behave differently on different os platforms. It does not work very well with Mac OS due to disabled Arial.ttf font that hase been disabled. I had to google a bit to get this resolved. To get the script working on my Mac (High Sierra v.10.13.4), I have to add ("theme(text=element_text(family="Garamond", size=14))") to all the ggplot functions in the R script file.

-----------------------------

Submission ID: #37

Decision: Reject (but more ‘borderline’)

Recommended for Best Artifact Awards: No

Score (out of 10): 5

Comments: The authors have explored the knowledge that developers retain during software development to ensure they are armed with pertinent details at a later stage of software evolution. The study comprised a literature review which was followed by interviews involving 17 developers, where the authors have outlined a number of relevant findings.

 

The authors claimed two badges, Available and Reusable, for the packaging of their data for other researchers to reuse.

 

In satisfying the Available criterion, the authors noted that “We make all of our methodological data (interview guide) and results (literature analysis, interview data) publicly (Zenodo) available. We also added notes that help to track the data to the paper. We registered a DOI (10.5281/zenodo.3972404) on Zenodo, but to be able to update the files if needed, we have not yet published the dataset on Zenodo.”. However, I was not able to locate the data while searching Zenodo, neither using the DOI or the paper title “What Developers (Care to) Recall: An Interview Survey on Smaller Systems”. I have provided the link to my search here: https://zenodo.org/communities/zenodo/search?page=1&size=20&q=What%20Developers%20(Care%20to)%20Recall:%20An%20Interview%20Survey%20on%20Smaller%20Systems.

 

Perhaps it would be better to add the paper title with the data as has been done by others? In fact, have you delayed the publishing of the data until now? I anticipated that the data would be published once your submission was made to the ICSME’20 Artifact track, and after the Kick-the-tires phase.

Of note is that most of the files were submitted on Git, however, I am not sure that we could accept that the artifacts are available if we are not able to sign off that these files are also publically hosted and researchers are able to access them.

 

In satisfying the Reusable criterion, the authors noted that “Providing the interview guide, we enable other researchers to reuse and replicate our study.”. While the interview guide was indeed available, and the manuscript with this document could form the basis for replicating the study, I anticipated that elements of replication should also be facilitated by the data and procedures that are available. So for instance, I should be able to replicate your study using your data, albeit I could then extend your work with new data as well. I could not always reuse the artifacts to easily replicate what was provided in the paper.

 

Specific comments are provided below in response to the Reusable badge, which at times may also be applicable to the Available request.

 

LiteratureData: All data files were available in the package as outlined, including: Collection_raw, ThemesFromClassifications, Reclassification, and Ratings. However, data were often included in one file, and at times a bit confusing (e.g., Collection_raw), needing quite a bit of time to make sense of its organisation. Replicating some of the plots in Figure 1 for the literature review was possible, however, there was need to reinstall various packages in R to confirm to versioning, this detail was not available as part of the submission, and thus could pose a challenge for others trying to replicate the results. For instance, while using ‘R version 3.6.0’, having imported all relevant packages, I got the error ‘Error in ggplot(values, aes(Class, Questions)) : could not find function "ggplot"’ when trying to generate the plots in Figure 1. Reinstalling the “ggplot2” package and reconfiguring some workspace settings allowed me to generate plots for (a) and (b), but I recorded another error when trying to generate (c) – “Error in fortify(data) : object 'counts' not found”.

 

InterviewData: All data files were available in the package as outlines, including: SurveyTemplate.pdf, IntervieweeeMeta, OS1-4, IK1, IK2 IK3, IK4_5, Correctness, Correctness_Code, and Correctness_Model, and TimesScienceFileEdits. However, as with the challenges replicating some of the figures for the LiteratureData, there were R errors when trying to generate some of the figures and other stats.

 

R: The R script and corresponding data files were available as outlined, including: script.R and a range of .csv files. It was also possible to replicate much of the results, notwithstanding the errors reposted above.

 

Overall, the authors have done a good job in their packaging of the source files for evaluation. However, there was need to make these files publically available, and provide a bit more direction for ensuring their reusability.

**Pull request merged**
