### PR TITLE
Paper #130 

### PR DESCRIPTION
**Pull request by leopoldomt**
This pull request contains the information required from our submission to the Artifact Evaluation Track, related to the ICSME'2020 paper #130 "Shake It! Detecting Flaky Tests Caused by Concurrency with Shaker". We apply for the reusable and available badges.

### CODE REVIEW

**Comment by icsme2020-review** [comment]
Dear authors, I am reviewing your artefact. I would need from you to update the artefact to allow for running on a Ubuntu Server - i.e. not to require a graphical interface.  Since you say that VirtualBox is not supported, it is very impractical to require a desktop installation.

**Comment by icsme2020-review** [comment]
Dear authors, I am continuing with the kick-off.  I had to do a several steps to install KVM, they are not described in the manual, so I am not sure if I did everything correctly. Unfortunately, when I run the emulator it crashes with:

failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
E0814 11:30:40.806615079    2230 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1597368640.806562312","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 15006 ms
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

crashhandler_die: fatal: kvm_arch_handle_exit: hardware error happened in KVM, aborting now


Do I understand correctly that you need to update the emulator? The manual did not say which version of Android studio to use - I had downloaded the latest available one

**Comment by anamean** [comment]
Dear authors, 
I am having similar issues to @icsme2020-review . The documentation does not say what is the expected run time or minimum system requirements (version numbers, memory requirements etc..) to run the package. I had to make a number of guesses about these requirements. This was really time consuming. 
Also, you mentioned that "The approach relies on running an emulator, and some steps might take long to execute, although we paremeterize our scripts so it is not necessary to run the exact number of replications we executed for each experiment in the paper". Can you please provide info about expected run time for each step so the reviewers can make the decision whether to run the whole analysis or part of it? 
Thanks

**Comment by leopoldomt** [comment]
Hi @icsme2020-review, are you running into this problem when running a Virtual Machine? We have been working on setting up a VM in VirtualBox during this week, but so far, our machine is unable to run the emulator too. It either freezes the VM or we end up with the same error from your comment. :( We are looking into it (got a more powerful machine to check if that's the issue and will try to fix it today still). Regarding the outdated emulator message, that is not a problem. 

Regarding @anamean's question, in each of the RQ folders at https://github.com/shaker-project/shaker/tree/master/evaluation, we have provided an expected runtime for the scripts, and we have also parameterised all of our code so one can choose to run less replications than we did for the paper. 

Thanks for your time!

**Comment by leopoldomt** [comment]
@icsme2020-review I was able to run the emulator including the -no-accel option. I am preparing the VM I am using to already include some apps that we evaluated inside the emulator, and will upload it tonight. Bear in mind that it is quite big (10Gb+), so it might be a while before I send the link (I am still configuring the emulator).

**Comment by leopoldomt** [comment]
@icsme2020-review @anamean I am waiting for the appliance to be exported (generating an .OVA file) and will upload it to a Google Drive folder. As soon as I am finished, I will post the link here.

**Comment by icsme2020-review** [comment]
Dear authors,
 yes the problem happened in the VM. Thanks for providing the VM, I will try it once it is uploaded

**Comment by icsme2020-review** [comment]
Dear authors, I can confirm that -no-accel runs the emulator.  However, I am not sure what to do next.

The instructions say:
"Manually install the apps using Android Studio. Do so by opening each project and choosing to run any AndroidTest, this way it will install the app and tests into the emulator device."

but this is too vague.  My guess was to run: 
~/android-studio-ide-193.6626763-linux/android-studio/bin$ ./studio.sh 

Then I guessed that I am suppose to import apps from:
 ll shaker/evaluation/projects/*

But what to do next? How to process with "to run any AndroidTest" ?

What next? The instructions say:

"Executing Shaker
This is all it takes for configuring the environment for running Shaker by using the predefined scripts for each research question from the paper, which are available at https://github.com/shaker-project/shaker."

I guess that I should run some more steps from Shaker, but the linked repository contains basically copy&paste of the same instructions. So I am not sure what to run next. Any scripts from the "evalution/rgX?"

**Comment by leopoldomt** [comment]
Hi @icsme2020-review, the `Shaker.ova` file can be found at https://drive.google.com/file/d/1tiNGC3X81vFjnEiS_H9VuuzeP4Dk0Wia/view?usp=sharing. You can import this file into VirtualBox (https://www.techjunkie.com/ova-virtualbox/). 

Yes, you would also need to install the apps in `~/projects` into the emulator. In the VM we provided an emulator with three apps already installed. The scripts and instructions in the `~/shaker/evaluation/` folder have been adapted to reflect the subset of apps installed in the emulator (we have also created the `vm` branch at https://github.com/shaker-project/shaker if you want to grab it from GitHub in your existing VM). So, we refer to the `README.md` file from each `~/shaker/evaluation/rqX` folder for the instructions.

**Comment by icsme2020-review** [comment]
Dear authors,

I successfully downloaded the VM, and executed the very first script, but it shows:

```
shaker@shaker-vm:~/shaker/evaluation/rq1$ python3 exec.py normal 3 2053
Number of ranges is 3
PID emulator is 3
running normal
Running ./exec.sh 0
android.util.AndroidException: INSTRUMENTATION_FAILED: com.orgzly.test/com.orgzly.android.OrgzlyTestRunner
	at com.android.commands.am.Instrument.run(Instrument.java:486)
	at com.android.commands.am.Am.runInstrument(Am.java:194)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

I had executed the emulator before this, given following output:

```
 emulator @d -no-accel  &
[1] 2053
shaker@shaker-vm:~/Android/Sdk/emulator$ emulator: WARNING: x86 emulation may not work without hardware acceleration!
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
failed to create drawable
E0815 06:08:42.119996459    2070 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1597482522.119950117","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

emulator: INFO: boot completed
emulator: INFO: boot time 135589 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
emulator: Revoking microphone permissions for Google App.

```

**Comment by leopoldomt** [comment]
Hi @icsme2020-review, in the updated instructions on the `rq` folders, such as `~/shaker/evaluation/rq1/README.md` (also available at https://github.com/shaker-project/shaker/blob/vm/evaluation/rq1/README.md), we recommend using a different emulator, since `@d` is quite heavy on the VM. Please try running the following commands before `python3 exec.py...`:
```
$ abd start-server
$ emulator @WVGA_API23 -no-accel -no-boot-anim &
```

**Comment by leopoldomt** [comment]
The `@WVGA_API23` emulator already contains a few apps installed, different than `@d`, which would need them to be installed prior to running the tests. I ended up forgetting to delete the `@d` emulator, sorry for the confusion. 

I also remembered that I placed a script that runs these two steps at `~/runemulator.sh`. You might need to use `ps` to grab the `PID` of the emulator.

**Comment by icsme2020-review** [comment]
Dear authors, 

I can confirm that after some work, it seems that the scripts are running (I see in the emulator that some tests run). So far I was able to experiment only with RQ1 as it has been running already half of the day. Thought the scripts run, I am not sure everything is ok, as I am getting following error:

python3 exec.py normal 3 2287
Number of ranges is 3
PID emulator is 3
running normal
Running ./exec.sh 0
the score is 0.26
[0.26]
Running ./exec.sh 1
the score is 0.30
[0.26, 0.3]
Running ./exec.sh 2
the score is 0.24
[0.26, 0.3, 0.24]
shaker@shaker-vm:~/shaker/evaluation/rq1$ python3 exec.py shaker 3 2287
Number of ranges is 3
PID emulator is 3
running shaker
Running ./exec_stress.sh 0 3 61 4 37 4 3
**taskset: failed to set pid 3's affinity: Invalid argument
./exec_stress.sh: line 29: stress-ng: command not found**

**Comment by icsme2020-review** [comment]
I would strongly suggest to have a look at all the scripts again and ideally provide one huge script that sets-up the environment and run all tests for all RQs. Otherwise one must spend days running a lot of scripts and checking every couple of hours if something is happening.

I understand that some steps related to installation of the Androind Studio may not be easy to automate. On the other hand, your documentation asks for a lot of steps, while they mostly consists only of copy+paste of commands in the console - this may be easily automated.

Moreover, a lot of steps are very vague (perhaps for someone familiar with Android development they are more clear). For instance, you ask for executing "abd start-server" - but it is not said where this program is and one needs to search file system.

**Comment by icsme2020-review** [comment]
Note: I was able to fix the problem 
./exec_stress.sh: line 29: stress-ng: command not found
by installing stress-ng

but I still see
taskset: failed to set pid 3's affinity: Invalid argument

**Comment by icsme2020-review** [comment]
Dear authors, 

for me to continue with evaluating this artefact I need following:
- one script (well two are acceptable as well) that runs all the experiments
- information how long it will run (potentially with ability to pause so I can run it overnight only)

With the current settings I am not able to meaningfully process this artefact.  You have provided 5 RQs and every RQ contains about 3-4 scripts.  Today I spent most of the day just running scripts from RQ1, and I am not done yet. It is not possible for me to spent approximately 1-week only with this artefact.

Even though the scripts provide some automation, one must check every couple of hours that the next script can be executed (I do not understand why the scripts are not executed automatically one-by-one).

Since you require the desktop machine, it is not possible for me to dedicate full time of the only desktop I have. I would not have problem to run non-stop on a server. I found some articles about running the emulator in a headless mode, but I cannot judge if this way was not possible. 

It is not clear how long the process may take - you mention 15h for RQ1, but I decreased the number of iteration to "3" only and I am already running several hours only one script - I use 8GB + 4CPU dedicated for the VM. If considerable more powerful machine is needed, then you should not expect a Desktop machine is available, but a server machine should be expected.

**Comment by leopoldomt** [comment]
We are preparing a setup and execution script that encompasses all steps. We are also checking whether running it on a server works for the purposes of the evaluation. The information about how long it will run is highly dependent on the machine which executes the steps. The 15h estimation for RQ1 was based on running it on a (not very powerful) laptop, however, without running it on top of a VM.

**Comment by leopoldomt** [comment]
> taskset: failed to set pid 3's affinity: Invalid argument

This usually refers to missing the emulator process or passing an incorrect value, from our experience.

**Comment by icsme2020-review** [comment]
Dear authors,
thanks for more information.  Although I run in the VM, I dedicated 8GB RAM + 4CPUs. I am not sure if this matches with "not very powerful laptop". But the experiment run the whole day and finally my laptop get restarted because it was overheated - I have Mackboook 16GB + 1.4GHz i5 - probably not too bad.  You should at least specify minimal requirements so one can start on a right configuration from beginning. 

About the error message - I am not aware of passing wrong arguments. This should be solved when you provide a script that does everything

**Comment by leopoldomt** [comment]
@icsme2020-review We have updated our repository (https://github.com/shaker-project/shaker) with new scripts and README instructions for setup and running the tool. 

The [`setup.sh`](https://github.com/shaker-project/shaker/blob/master/setup.sh) performs the entire configuration of the environment, installing all required packages, and creating the emulators. 

The [`runemulator.sh`](https://github.com/shaker-project/shaker/blob/master/runemulator.sh) starts the emulator. After starting for the first time, you might use [`install-apps.sh`](https://github.com/shaker-project/shaker/blob/master/install-apps.sh) to install the APKs for all of the apps we evaluated for the paper. 

In the [`evaluation`](https://github.com/shaker-project/shaker/tree/master/evaluation) folder, we have created dedicated scripts for each RQ, and the [`runall.sh`](https://github.com/shaker-project/shaker/blob/master/evaluation/runall.sh) script, which calls all scripts in sequence. To make it easier to run this script, we have created two drivers, namely [`icsme2020-eval.sh`](https://github.com/shaker-project/shaker/blob/master/evaluation/icsme2020-eval.sh) and [`quick-eval.sh`](https://github.com/shaker-project/shaker/blob/master/evaluation/quick-eval.sh). The first script performs the evaluation using the same settings as we used for the paper. The second one uses a minimal number of reexecutions and configurations for running the evaluation. One can also modify the number of executions, configurations, and so on, to perform the evaluation. 

We have reviewed the python scripts for issues such as the one related to `taskset`, as well. 

We are having trouble uploading the new version of the VM (already configured using this new setup), but will try it again during the night (we believe it might be a more stable connection). As soon as we're done uploading (probably early morning tomorrow - Brazil time), we will post the link here.

**Comment by leopoldomt** [comment]
> Although I run in the VM, I dedicated 8GB RAM + 4CPUs. I am not sure if this matches with "not very powerful laptop". But the experiment run the whole day and finally my laptop get restarted because it was overheated - I have Mackboook 16GB + 1.4GHz i5 - probably not too bad. You should at least specify minimal requirements so one can start on a right configuration from beginning.

The experiments conducted for the paper were executed on the following configuration: [Intel Core i5-7200U](https://ark.intel.com/content/www/us/en/ark/products/95443/intel-core-i5-7200u-processor-3m-cache-up-to-3-10-ghz.html) CPU @ 2.50 GHz, with 8Gb RAM and 240Gb SSD, running Ubuntu 18.04 LTS

Forgot to mention, that the repository now also contains a branch named `quick`, in which the majority of the tests are commented out, so it can provide an even faster running time.

**Comment by leopoldomt** [comment]
The new version of the VM can be found at https://drive.google.com/file/d/1BBb4uBah0gUyufMhM7WioX1wKowbttHd/view?usp=sharing.

**Comment by icsme2020-review** [comment]
Dear authors,

the scripts now look much more usable - I was able to set-up environment automatically on a clean VM. Very appreciated.

Unfortunately, there are still some bugs in the scripts:

When I run, the emulator it shows:
 ./runemulator.sh
./runemulator.sh: line 7: type: adb: not found
Setting environment variables for adb and emulator
* daemon not running; starting now at tcp:5037
* daemon started successfully

Since the emulator starts, it is not clear if the previous error message causes actually any problem. But  when I try to execute quick-eval.sh it prints a lot of lines showing:

./exec.sh: line 50: adb: command not found
./exec.sh: line 52: adb: command not found
./exec.sh: line 54: adb: command not found
./exec.sh: line 56: adb: command not found
./exec.sh: line 58: adb: command not found
./exec.sh: line 60: adb: command not found
./exec.sh: line 62: adb: command not found
./exec.sh: line 64: adb: command not found
./exec.sh: line 66: adb: command not found
./exec.sh: line 68: adb: command not found
./exec.sh: line 70: adb: command not found
./exec.sh: line 72: adb: command not found
./exec.sh: line 74: adb: command not found
./exec.sh: line 76: adb: command not found
./exec.sh: line 78: adb: command not found
./exec.sh: line 80: adb: command not found
./exec.sh: line 82: adb: command not found
./exec.sh: line 84: adb: command not found
./exec.sh: line 86: adb: command not found
./exec.sh: line 88: adb: command not found
./exec.sh: line 90: adb: command not found
./exec.sh: line 92: adb: command not found
./exec.sh: line 94: adb: command not found
./exec.sh: line 96: adb: command not found
./exec.sh: line 98: adb: command not found
./exec.sh: line 100: adb: command not found
./exec.sh: line 102: adb: command not found
./exec.sh: line 104: adb: command not found
./exec.sh: line 106: adb: command not found
./exec.sh: line 108: adb: command not found
./exec.sh: line 110: adb: command not found
./exec.sh: line 112: adb: command not found
./exec.sh: line 114: adb: command not found
./exec.sh: line 116: adb: command not found
./exec.sh: line 118: adb: command not found
./exec.sh: line 120: adb: command not found
./exec.sh: line 122: adb: command not found
./exec.sh: line 124: adb: command not found
./exec.sh: line 126: adb: command not found
./exec.sh: line 128: adb: command not found

**Comment by leopoldomt** [comment]
Hi @icsme2020-review, it seems that the export variables script ([`setvars.sh`](https://github.com/shaker-project/shaker/blob/master/setvars.sh)) is not working to change the actual environment. Please, run `source setvars.sh` (this script is located at the main `shaker` folder) before running `quick-eval.sh`, that should enable you to run the evaluation. I will work on fixing the setup script so that environment variables are permanently set.

**Comment by icsme2020-review** [comment]
Dear authors, 
I run the experiment on the server via the no-gui option. I think that RQ1 run, but then I started to get these errors:

cmd: Can't find service: settings  
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
        at com.android.commands.am.Am.onRun(Am.java:68)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
        at com.android.commands.am.Am.onRun(Am.java:68)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
./exec.sh: line 126: kill: (3284528) - No such process
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
runing ./exec.sh 0 1 61 1 73 4 3 espresso 2882194
Value 61% contains non-numeric: '%'
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
        at com.android.commands.am.Am.onRun(Am.java:68)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
        at com.android.commands.am.Am.onRun(Am.java:68)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
Error type 2
android.util.AndroidException: Can't connect to activity manager; is the system running?
        at com.android.commands.am.Am.onRun(Am.java:68)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
./exec.sh: line 126: kill: (3299978) - No such process
cmd: Can't find service: settings
cmd: Can't find service: settings
cmd: Can't find service: settings
runing ./exec.sh 0 1 34 1 37 1 4 espresso 2882194
Value 34% contains non-numeric: '%'
cmd: Can't find service: settings



I cannot get the full log a I run in a screen. I tried to redirect via  "> file.txt", but it was not working - I am not sure why

**Comment by icsme2020-review** [comment]
Dear authors, I re-run the experiment again and I was able to capture first part of the result. It seems that the scripts are somehow running, but it produces some error outputs:

 =============================================
 ================ RUNNING RQ1 ================
 =============================================

 >>>> Running Standard Execution environment
Number of ranges is 1
PID emulator is 3580235
running normal
Running ./exec.sh 0


the score is 1.00
[1.0]

 >>>> Running Noisy Execution environment
Number of ranges is 1
PID emulator is 3580235
running shaker
Running ./exec_stress.sh 0 3 61 4 37 4 3580235
Value 61% contains non-numeric: '%'
./exec_stress.sh: line 263: kill: (3582893) - No such process
the score is 1.00
[1.0]

 >>>> Calculating stats for RQ1
Traceback (most recent call last):
  File "rq1.py", line 2, in <module>
    from scipy import stats
ModuleNotFoundError: No module named 'scipy'

**Comment by icsme2020-review** [comment]
Dear authors, I was able to capture log for RQ2, it also shows some error messages:

 =============================================
 ================ RUNNING RQ2 ================
 =============================================

 >>>> Executing Noise Configurations to test variance of results
number of ranges is 1
number repeat is 1
PID emulator is 3580235
running ./exec_stress.sh 0 2 2 1 21 2 0 3580235
Value 2% contains non-numeric: '%'


^[[A


^[[A./exec_stress.sh: line 262: kill: (3585089) - No such process
the score is 1.00
[[1.0]]
Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 'results.txt'
config 1 -> sd: NA mean: 1 
mean std. deviation -> NA 
Error in plot.window(ylim = xlim, xlim = ylim, log = log, xaxs = pars$yaxs) : 
  need finite 'xlim' values
Calls: boxplot -> boxplot.default -> do.call -> bxp -> plot.window
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted

**Comment by leopoldomt** [comment]
> Dear authors,
> I run the experiment on the server via the no-gui option. I think that RQ1 run, but then I started to get these errors:
> 
> cmd: Can't find service: settings
> Error type 2
> android.util.AndroidException: Can't connect to activity manager; is the system running?
> at com.android.commands.am.Am.onRun(Am.java:68)
> at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
> at com.android.commands.am.Am.main(Am.java:50)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> Error type 2
> android.util.AndroidException: Can't connect to activity manager; is the system running?
> at com.android.commands.am.Am.onRun(Am.java:68)
> at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
> at com.android.commands.am.Am.main(Am.java:50)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> ./exec.sh: line 126: kill: (3284528) - No such process
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> runing ./exec.sh 0 1 61 1 73 4 3 espresso 2882194
> Value 61% contains non-numeric: '%'
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> Error type 2
> android.util.AndroidException: Can't connect to activity manager; is the system running?
> at com.android.commands.am.Am.onRun(Am.java:68)
> at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
> at com.android.commands.am.Am.main(Am.java:50)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> Error type 2
> android.util.AndroidException: Can't connect to activity manager; is the system running?
> at com.android.commands.am.Am.onRun(Am.java:68)
> at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
> at com.android.commands.am.Am.main(Am.java:50)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> Error type 2
> android.util.AndroidException: Can't connect to activity manager; is the system running?
> at com.android.commands.am.Am.onRun(Am.java:68)
> at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
> at com.android.commands.am.Am.main(Am.java:50)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> ./exec.sh: line 126: kill: (3299978) - No such process
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> cmd: Can't find service: settings
> runing ./exec.sh 0 1 34 1 37 1 4 espresso 2882194
> Value 34% contains non-numeric: '%'
> cmd: Can't find service: settings
> 
> I cannot get the full log a I run in a screen. I tried to redirect via "> file.txt", but it was not working - I am not sure why

I believe this is related to the screen not showing on the emulator. `Activity manager` is the Android system responsible for managing screens.

**Comment by leopoldomt** [comment]
> Dear authors, I re-run the experiment again and I was able to capture first part of the result. It seems that the scripts are somehow running, but it produces some error outputs:
> 
> # =============================================
> ================ RUNNING RQ1 ================
> > > > > Running Standard Execution environment
> > > > > Number of ranges is 1
> > > > > PID emulator is 3580235
> > > > > running normal
> > > > > Running ./exec.sh 0
> 
> the score is 1.00
> [1.0]

Score 1.0 means that all tests are failing, so I believe that running it in the server (it's a different setup than what we have used) seems to cause this behaviour.

> > > > > Running Noisy Execution environment
> > > > > Number of ranges is 1
> > > > > PID emulator is 3580235
> > > > > running shaker
> > > > > Running ./exec_stress.sh 0 3 61 4 37 4 3580235
> > > > > Value 61% contains non-numeric: '%'
> > > > > ./exec_stress.sh: line 263: kill: (3582893) - No such process
> > > > > the score is 1.00
> > > > > [1.0]
> 
> > > > > Calculating stats for RQ1
> > > > > Traceback (most recent call last):
> > > > > File "rq1.py", line 2, in 
> > > > > from scipy import stats
> > > > > ModuleNotFoundError: No module named 'scipy'

This is weird, as the `setup.sh` also includes commands for installing scipy through `pip install`.

**Comment by leopoldomt** [comment]
> Dear authors, I was able to capture log for RQ2, it also shows some error messages:
> 
> # =============================================
> ================ RUNNING RQ2 ================
> > > > > Executing Noise Configurations to test variance of results
> > > > > number of ranges is 1
> > > > > number repeat is 1
> > > > > PID emulator is 3580235
> > > > > running ./exec_stress.sh 0 2 2 1 21 2 0 3580235
> > > > > Value 2% contains non-numeric: '%'
> 
> ^[[A
> 
> ^[[A./exec_stress.sh: line 262: kill: (3585089) - No such process
> the score is 1.00
> [[1.0]]
> Warning message:
> In read.table(file = file, header = header, sep = sep, quote = quote, :
> incomplete final line found by readTableHeader on 'results.txt'
> config 1 -> sd: NA mean: 1
> mean std. deviation -> NA
> Error in plot.window(ylim = xlim, xlim = ylim, log = log, xaxs = pars$yaxs) :
> need finite 'xlim' values
> Calls: boxplot -> boxplot.default -> do.call -> bxp -> plot.window
> In addition: Warning messages:
> 1: In min(x) : no non-missing arguments to min; returning Inf
> 2: In max(x) : no non-missing arguments to max; returning -Inf
> Execution halted

The score as 1.00 also relates to all tests failing (as mentioned in a previous comment). 

The error below is related to the R script, again, I believe that this is due to not being on a screen, as the script tries to produce a plot.

**Comment by icsme2020-review** [comment]
well, what should I do now? I thought that the scripts were updated to run on the server.

**Comment by leopoldomt** [comment]
> well, what should I do now? I thought that the scripts were updated to run on the server.

I am not sure about this. We have updated the scripts to ensure that we could run it in a VM similar to the setup we used. We could not make sure that it would work on a server, since that was not the setup we used.

**Comment by jensdietrich** [comment]
Thanks for the discussion. I would like to remind the authors that the kick-the-tires phase has ended on 14 August, so assessment of the artifact now is based on what is provided (artifact and submitted instructions).

**Comment by klainfo** [comment]
Thank you for submitting the artefact to the ICSME'20 Artifact/Rose Track. Three reviewers have rigorously reviewed the research artefact. Three of them discovered that the artifact is not reusable due to several installation problems. Thus, we are sorry to inform that there is no badge assigned to this artefact submission.

-----------------------------
Submission ID: #130
Decision: Reject
Recommended for Best Artifact Awards: N
Score (out of 10): 3.5
Comments: w.r.t. Badge Rubrics

The artifact is available on GitHub but not sure if it is actually functional. I had several issues running this one. I tried this multiple times already. The artifact is not well explained and steps are not well documented. 

Tested on two machines :

MacOS 10.16.6 on 2.6GHZ 8CPUs and 16 GB  dedicated RAM → Results: Unable to run the emulator successfully.

Ubuntu 18.04.4 LTS desktop edition on 3.20GHZ 12CPU and 32GB RAM →  Results: the emulator ran successfully but the scripts to create the results have all failed.

The following scripts produced the same error messages as the ones Kamil posted on the repository: RQ1.sh RQ2.sh and icme2020-eval.sh. I have attached the error message I got from RQ2.

-----------------------------

Submission ID: #130

Decision: Reject

Score: 5/10

Comments: README was excellent. Installation was fine. But, when I run, there was errors saying INSTRUMENTATION_ERROR for all the RQs.

-----------------------------

Submission ID: #130
Decision: Reject
Recommended for Best Artifact Awards: No
Score (out of 10): 3
Comments:

I appreciate work invested by authors into this artefact. Their tool is available online in GIT with rich README provided. I guess with some effort and tight communication with the authors, other parties would be able to re-use this work. 

Unfortunately, it is not straightforward to  reuse the artefact at the moment. First, authors laid too narrow software requirements, i.e. only a desktop Ubuntu 18.04, while it is not clear why the requirement was set-up so strict. A brief analysis and back-and-forth experimenting showed that with minimal modifications (different runtime parameters of AndroidStudio), the experiment may run on a headless Ubuntu Server as well, or in a VM.  I would suggest to authors next time to think of re-usability in more wider meaning, and do not bound re-usability to the context of environment matching the authors environment they accidentally had available for their experiment. 

Furthermore, the README had a lot of steps where some of them were not detailed deeply enough. For instance, it asked to run “abd start-server”, but did not mention where this script is located - it is actually in AndroidStudio subfolders and I had to search the file-system. Similar problem holds for the script “studio.sh”.

Authors tried to improve their scripts in the initial phase of the review, but the scripts were never fully working. From the output, one may guess that some packages were missing, or some processes did not start. It seems that the main source of these problems is that authors forget to install some packages via the scripts and they had them accidentally in their system. Next time I would suggest authors to provide better automation, ideally a Docker image that installs all prerequisities and assures that it runs exactly the same enywhere. 

As a consequence of above mentioned, I was not able to successfully run the scripts for any of the RQs.

**Pull request closed without merging**
