### PR TITLE
Paper 42

### PR DESCRIPTION
**Pull request by liyistc**
Applying for available and reusable badges.

### CODE REVIEW

**Comment by icsme2020-review** [comment]
kick-off passed - the demo script run without problem. The full script has started and is running.

**Comment by reviewertwo** [comment]
sorry for my late reply, I think that the readme should have some pre-requisites. For example, authors assume that everyone is familiar with docker. I suggest you add some versions for installations or also that they should clone the git repo first.

**Comment by icsme2020-review** [comment]
Dear authors,
I am running the full script, but it runs already 3 days.  The most recent lines (which I think hangs at least two days) say:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Commons Configuration 2.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-3) @ commons-configuration2 ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ commons-configuration2 ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.3.201502191951:prepare-agent (default-prepare-agent) @ commons-configuration2 ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.3.201502191951/org.jacoco.agent-0.7.3.201502191951-runtime.jar=destfile=/home/genslice/_downloads/commons-configuration/target/jacoco.exec
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (javadoc.resources) @ commons-configuration2 ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- javacc-maven-plugin:2.6:javacc (javacc) @ commons-configuration2 ---
[INFO] Skipping - all parsers are up to date
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ commons-configuration2 ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ commons-configuration2 ---
[INFO] Executing: /bin/sh -c cd '/home/genslice/_downloads/commons-configuration' && 'svn' '--non-interactive' 'info'
[INFO] Working directory: /home/genslice/_downloads/commons-configuration
[WARNING] Cannot get the revision information from the scm repository, proceeding with revision of ?????? : 
Exception while executing SCM command.
[INFO] Storing buildNumber: ?????? at timestamp: 1597297663096
[INFO] Executing: /bin/sh -c cd '/home/genslice/_downloads/commons-configuration' && 'svn' '--non-interactive' 'info'
[INFO] Working directory: /home/genslice/_downloads/commons-configuration
[WARNING] Cannot get the branch information from the scm repository, proceeding with UNKNOWN_BRANCH : 
Exception while executing SCM command.
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ commons-configuration2 ---
[INFO] Using 'iso-8859-1' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 2 resources to META-INF
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ commons-configuration2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 258 source files to /home/genslice/_downloads/commons-configuration/target/classes
[INFO] /home/genslice/_downloads/commons-configuration/src/main/java/org/apache/commons/configuration2/AbstractConfiguration.java: Some input files use or override a deprecated API.
[INFO] /home/genslice/_downloads/commons-configuration/src/main/java/org/apache/commons/configuration2/AbstractConfiguration.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/genslice/_downloads/commons-configuration/src/main/java/org/apache/commons/configuration2/MapConfiguration.java: /home/genslice/_downloads/commons-configuration/src/main/java/org/apache/commons/configuration2/MapConfiguration.java uses unchecked or unsafe operations.
[INFO] /home/genslice/_downloads/commons-configuration/src/main/java/org/apache/commons/configuration2/MapConfiguration.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-bundle-plugin:3.0.1:manifest (bundle-manifest) @ commons-configuration2 ---
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.15:check (checkAPIcompatibility) @ commons-configuration2 ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ commons-configuration2 ---
[INFO] Using 'iso-8859-1' encoding to copy filtered resources.
[INFO] Copying 116 resources
[INFO] Copying 2 resources
[INFO] Copying 2 resources to META-INF
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ commons-configuration2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ commons-configuration2 ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.commons.configuration2.spring.TestConfigurationPropertySource
log4j:WARN No appenders could be found for logger (org.springframework.test.context.junit4.SpringJUnit4ClassRunner).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.601 s - in org.apache.commons.configuration2.spring.TestConfigurationPropertySource
[INFO] Running org.apache.commons.configuration2.spring.TestConfigurationPropertiesFactoryBean
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 s - in org.apache.commons.configuration2.spring.TestConfigurationPropertiesFactoryBean
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.081 s
[INFO] Finished at: 2020-08-13T05:47:48+00:00
[INFO] Final Memory: 35M/876M
[INFO] ------------------------------------------------------------------------
Saved working directory and index state WIP on orig: 9fb4ad8 Updated building documentation.
HEAD is now at 9fb4ad8 Updated building documentation.
===> Splitting ...

**Comment by Chenguang-Zhu** [comment]
> sorry for my late reply, I think that the readme should have some pre-requisites. For example, authors assume that everyone is familiar with docker. I suggest you add some versions for installations or also that they should clone the git repo first.

Thanks for pointing it out! The pre-requisites are:
1. Clone the Git repo of the artifact: https://github.com/Chenguang-Zhu/icsme20-artifact
2. Install docker version 19.03.12.

We have also updated the readme files in the pull request.

**Comment by liyistc** [comment]
@icsme2020-review Thanks for trying it out. We have repeated the experiments five times and haven't experienced this before. Could you please send us the console log (or at least knowing which config is causing the issue), so that we can try to replicate it on our end?

**Comment by icsme2020-review** [comment]
Dear authors, the console output is enclosed.  I had run:

docker run --name genslice-all -i -t genslice --rm -v `pwd`:/Scratch
./run_all.sh

[log.txt](https://github.com/se-conf/icsme20-artifacts-and-rose/files/5079718/log.txt)

**Comment by liyistc** [comment]
@icsme2020-review Thanks for pointing out the issue! It turns out that we've mistakenly included an older version of the script. Please check out the newer version at: https://github.com/Chenguang-Zhu/icsme20-artifact, rebuild the docker image (`docker build -f Dockerfile -t genslice .`), and rerun the full script (using the same commands; remove the existing `genslice-all` container in case docker complains). It should work now.

We've also updated the replication package at the permanent DOI. Please feel free to let us know if there's any issue.

**Comment by liyistc** [comment]
@icsme2020-review The 40.5 hours is an underestimation (it's the time taken by 7 configurations). The full experiment script (running 13 configurations) takes more than that. I'm also running it since the last fix and still have about 1/4 cases remaining. My updated estimation would be about 4 days.

**Comment by klainfo** [comment]
Thank you for submitting the artefact to the ICSME'20 Artifact/Rose Track. Congratulations! Three reviewers agreed that the artefact is reusable and available.

-----------------------------

Submission ID: #42
Decision: Accept
Recommended for Best Artifact Awards: Yes
Score (out of 10): 9
Comments:  I appreciate work done by the authors on this artefact. The artefact is based on a Docker image, which means that others need only to build and run the image. All the experiments are performed automatically. Authors provide two versions of the scripts, one for a quick (demo) run and the other one runs full experiments. I had no single issue with the artefact and it run as described. Thanks to Docker, the experiment may run on a variety of platforms - desktop, server, MacOS, Linux, Windows (with Linux subsystem).  This is an example of a well prepared, versatile artefact. 

I would suggest the authors to create a script that collects the results and produce charts/tables resembling the presentation in the paper.  Currently, it is difficult to match the results with the paper. This would be necessary for more advanced badges such as Replicated. However, this is not the case for this submission. 

I recommend the artefact to be awarded with both badges Reusable and Available

-----------------------------

Submission ID: #42
Decision: Accept
Recommended for Best Artifact Awards: No
Score (out of 10): 7
Comments:

This artifact is available and reusable (although not 100% functional
on my environment).

The artifact can be exercised in two ways: for a "demo case" and for
the "full experiment". Both cases are documented in the README but I
could not run the second one (the authors should see Issue 1 below for
possible tweaks to the artifact).

Although I could not run the full experiment in its entirety, I
understand that this is sometimes to be expected from very heavy
artifacts, so this should not disqualify this artifact from being
marked as functional.

The README is well-written and easy to follow to be able to run the
(quite useful) demo case. There is documentation about the output
format, so that output can be reused. Also, the full-experiment script
(run_all.sh) is easy to understand/edit to isolate parts of the
experiment. I believe that adding more programs to test would need
tweaking the few variables on top of the script (although there was
some ad-hoc logic to handle programs such as pdfbox).

== Issue 1 ==

Running the full experiment took more than "~40.5 hours" on a
256GB RAM server: after executing for more than two days, the script
crashed with the following error:

```
Starting Example :COMPRESS-374
remove old repo
===> Splitting ...
Traceback (most recent call last):
  File "genslice/genslice.py", line 5503, in <module>
      runSplitDefiner(example, share_prefix, share_suffix)
        File "genslice/genslice.py", line 1346, in runSplitDefiner
            repo_path=repo_path, branch='after-split')
              File "genslice/genslice.py", line 1057, in genSplitLogFile
                  fw = open(split_log, 'w')
                  OSError: [Errno 28] No space left on device: '/home/genslice/genslice/../file-level/output/split-definer/COMPRESS-374.log.split'
```

I suspect this is due to the 10GB limit imposed by Docker on filesystem containers and should be addressed by the authors.

== Issue 2 ==

I had a problem with this invocation (from the README), which did not
set up the bind/volume for /Scratch:

```bash
docker run --name genslice-all -i -t genslice --rm -v `pwd`:/Scratch
```

This reordering of arguments fixed the problem (and should be updated in the README):

```bash
docker run --rm -v `pwd`:/Scratch --name genslice-all -i -t genslice
```

My Docker version:

```bash
$ docker --version
Docker version 19.03.8, build afacb8b
```

-----------------------------

Submission ID: #42
Decision: Accept
Recommended for Best Artifact Awards: No
Score (out of 10): 9
Comments:
I added some comments on the installation steps, but overall I was able to execute.
The whole replication did take over 40 hours, I commend that authors to making the whole process replicable.

**Pull request merged**
